### ISSUE TITLE
download

### ISSUE THREAD

**Issue by bluesksksk** [SKCraft/Launcher#119]
When my friend want to download modpack it say this but for me it work

http://postimg.org/image/mxrzwxy69/

**Comment by bluesksksk** [comment]
this error show when my friend try to login to premium account not when downloading

**Comment by rouing** [comment]
Looks like an SSL Error. Check the System Time and make sure that the *.minecraft.com Cert is trusted on the computer.

**Comment by bluesksksk** [comment]
what?

**Comment by ajthemacboy** [comment]
It's like jtrent238 all over again.

**Comment by dj3520** [comment]
Use Google sir

**Comment by wizjany** [comment]
or at least provide the full error, not a minuscule screenshot of half an error.

**Comment by jtrent238** [comment]
Try to run you application with `-Djavax.net.ssl.trustStore` parameter. Verify which JDK/JRE you are using too as this is often a source of confusion.

The source of this error on my Apache 2.4 instance (using a Comodo wildcard certificate) was an incomplete path to the SHA-1 signed root certificate. There were multiple chains in the issued certificate, and the chain leading to a SHA-1 root certificate was missing an intermediate certificate. Modern browsers know how to handle this, but Java 7 doesn't handle it by default (although there are some convoluted ways to accomplish this in code). The result is error messages that look identical to the case of self-signed certificates:

```
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
    at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
    at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
    ... 22 more
```

In this case, the "unable to find valid certification path to requested target" message is being produced due to the missing intermediate certificate. You can check which certificate is missing using SSL Labs test against the server. Once you find the appropriate certificate, download it and (if the server is under your control) add it to the certificate bundle. Alternatively, you can import the missing certificate locally. Accommodating this issue on the server is a more general solution to the problem.
