### ISSUE TITLE
prevent use of external mods.

### ISSUE THREAD

**Issue by mblob** [SKCraft/Launcher#139]
Once the launcher created the directory structure of the instance, nothings prevent user to drop any jar in the mod folder and use it.

Would it be possible for the launcher to check against a mod list, directory hash, whatever, and prevent launch if the check failed ?

I have no idea how the launcher works, i just hope its possible cause i get tired of cheaters.

**Comment by ajthemacboy** [comment]
Interesting idea to prevent X-ray mods and all that. One problem is that the user could just move the mods to the vanilla launcher and use a Forge instance.

**Comment by Nincodedo** [comment]
Are you trying to prevent people from using cheats on a server? Because I'm pretty sure [Mod Control](http://minecraft.curseforge.com/projects/mod-control) can do that for you.

**Comment by mblob** [comment]
Mod control does not block xray. 
I guess the perfect solution would be to implement a mod both server/client where client mod would send the hash of the mod/ressourcepack directory or something like tht.

**Comment by ajthemacboy** [comment]
@mblob  I don't mean this feature would be used to specifically block XRay. What I meant was, the only practical use I can see for this is to prevent users from adding hack/cheat mods to the modpack. 

An example of that is the XRay mod, which is literally just drag-and-drop to install.

**Comment by mblob** [comment]
yep i was answering about xray cause it is the most obvious one. It would be great, in any case, to prevent any modification of the modpack.

**Comment by ajthemacboy** [comment]
Oh, I misread your comment, sorry.

**Comment by kayila** [comment]
If this does get put in as requested (A mechanism that makes the launcher always force the mod pack to be unmodified) I'd like it to be an optional thing... Some mods edit their own mods folder or config file as part of normal operation, and certain mod packs I'm ok with end users adding in mods to customize their experience some.

**Comment by wizjany** [comment]
there is no mechanism whatsoever that can secure the client completely. in ANY application, when there is server<->client communication, a malicious client can ALWAYS lie if it wants to. similarly, a user can trivially install a modpack via the launcher, modify as they wish, and launch it manually, circumventing any checks the launcher could be using.

**Comment by jtrent238** [comment]
[PackGuard](http://bit.ly/1Q470qs)

**Comment by wizjany** [comment]
addresses literally 0 of the issues at hand. literally 0.
all it does it warn the user if the modpack has been changed. if the user added an xray mod, do you really think they care about that warning?

**Comment by jtrent238** [comment]
The "I Understand, Let Me Continue!" Button Can Be Removed Via Config "I Think"

**Comment by wizjany** [comment]
that doesn't help...

**Comment by ajthemacboy** [comment]
The problem with PackGuard is that the user could just disable it in the config and you're fine, or copy the mods to another instance and your fine.

The best solution I can think of is to have the modpack launcher communicate with the server itself:

If the modpack has been launched via an unmodified launcher instance (verified by a list of MD5s of both mods and config) the launcher will communicate with a serverside mod or plugin. 

If the pack has been launched via another launcher or another instance, then it won't communicate with the server or it will communicate that the modlist/config is different, and the server won't allow the player to join.

The launcher could be modified to communicate a certain MD5 list, or the vanilla MD5 list, but most users wouldn't have the knowledge required to go around this by cloning the source and compiling it. (I have a hard enough time explaining that my players need Java 8!)

If you wanted to be **_really_** secure, you could have the launcher send a MD5 of _**itself**_ to the server to compare against a set MD5 to see if the launcher has been modified. Each individual server could add some text to various launcher source files to make the MD5 of a particular server's launcher completely unique. Even if/when someone modifies SK's launcher to allow extra mods, a generic MD5 won't work since the server.properties is different, meaning that the user attempting to modify the modlist would have to calculate his own MD5s and code the cracked launcher to send that MD5 to the server. (Most of what I just said can be erased because the launcher.properties file is unique to each server, but still it's good for the paranoid to more files.)

**Comment by dj3520** [comment]
I think that would be the way to do it except that if I learned the md5 hash that needs sent I could make a client that sends that instead of it's actual hash, defeating the system again. Maybe something like a public/private key system. Either way I feel like this is a separate project considering the server would have to accept/reject, and this is just a launcher.

**Comment by ajthemacboy** [comment]
Right dj3520, I said that in so many words above, albeit rather incoherently. However no one I know would put that much effort into bypassing the launcher, and most of my players aren't skilled enough to anyway.

**Comment by sk89q** [comment]
Public/private keypair doesn't fix it because the client would have the private key and could do whatever they wanted with it.

While I see this is achievable to stop non-technically inclined folk *initially* (until someone releases something to defeat it), it would require a lot of maintenance to keep everything up to date. Right now the launcher is pretty MC version-agnostic (it doesn't even know about Forge or LiteLoader) so I want to keep it that way so MC updates rarely break anything.
