### ISSUE TITLE
Signable files

### ISSUE THREAD

**Issue by dscso** [SKCraft/Launcher#145]
I think it would be nice if I be able to sign all files using something like GPG to prevent downloading malware (like Debian package manager (aptitude) does). I know it's also possible to use HTTPS but letsencrypt.org certificates are not supported (Java) and it's not needed to encrypt whole traffic...
https://github.com/SKCraft/Launcher/issues/119

**Comment by James137137** [comment]
you can still use letsencrypt but you need to add letsencrypt public ssl key with your launcher

**Comment by dscso** [comment]
How?
Java has normaly no let's encrypt root CA's installed. I thougt about a line in the configuration where you can add the (as example GPG) public key, and if the files are not signed correctly the launcher abouts downloading...
If you think thats to complicated it would ne nice to add the server public key in the configuration and just use SSL...

**Comment by spannerman79** [comment]
I've been keeping an eye on this trying to work out exactly what the OP was trying to ask.

It would be "better" if SHA-256 checksum was used instead of GPG but as some mod developers require that their mod comes from a particular source (curse for the example of journeymap) your issue is null and void.

**Comment by dscso** [comment]
I don't understand what you want to say.
As far as I can see encrypting/signing traffic/files makes no difference if we are stil talking about usage rights.

**Comment by wizjany** [comment]
because some mod authors require users to download their mods off curse, and we have no control over how curse distributes their files, etc.

**Comment by sk89q** [comment]
The launcher currently stores a (only) SHA-1 hash of each file. The launcher does use it to verify changes but I'm not sure it uses it to verify integrity of authenticity.

It's low priority but the easiest way to solve this problem is:

1. Add Let's Encrypt's certs to the launcher or add a way to bundle certs.
2. Serve the package manifests over SSL.
3. Upgrade the hashing algorithm.
4. Use the hash to check integrity and authenticity.

The fact that you might load a mod off Curse or some external site doesn't change anything. The launcher supports that already, hash included.

**Comment by danielsteiner** [comment]
Awesome that this issue is brought up - I've been trying to serve files via a site that uses a Let's Encrypt certificate some month back but failed. the only workaround I found was to add the LE pubkey to the trusted root ca storage in windows but that's not an option if you want to distribute the launcher to your friends.

**Comment by dscso** [comment]
Yes.
I also thought about keys because your can still use HTTP because its more flexible and safer. The cons are that you have to generate them, sign everything,... That can be too complicated for some kind of people who don't read the docs (like me).

**Comment by danielsteiner** [comment]
Btw i also have an issue with logging in via a proxy. Any ideas on that other than ssl spoofing (or a man in the middle aproach?)

**Comment by wizjany** [comment]
@kenzierocks also had issues logging in with a proxy on a day or two ago, but I haven't heard of this before then...is this a new issue? Have you guys been using a proxy for a while? If so, does that mean Mojang recently made some changes that broke that? (this should probably be a new issue btw, you derailed the thread @danielsteiner )

**Comment by danielsteiner** [comment]
No idea will test that in a few days.

**Comment by kenzierocks** [comment]
@danielsteiner Report results to #147 instead, to keep issues on topic.

**Comment by dscso** [comment]
So do *you* think to sign all this files makes sense?

**Comment by sk89q** [comment]
SSL is a lot easier than signing the package listing and manifest files.

**Comment by dscso** [comment]
Its this annoying PKI. Thats old and not secure. I will try to add the opportunity to store the server public key/CA in the Launcher/Bootstrapper. The problem is that you need to update the CA's every ca. 5 years... It's a lot of pain...

**Comment by James137137** [comment]
On my version of the launcher I did this: https://github.com/James137137/LolnetLauncher/commit/82d74e4c795f4e66e3e7db6ec9c6532e076a5092 its a lazy way as it accepts all certificates (including self-signed) I should look at updating this tho....

**Comment by wizjany** [comment]
doesn't that kind of defeat the purpose?

**Comment by James137137** [comment]
yeah. I suppose it would. well there's always 

keytool -import -v -trustcacerts -alias IdenTrust -keypass yourpassword -file dst_root_ca_x3.pem -keystore cacerts.jks -storepass yourpassword

**Comment by sk89q** [comment]
The 3.x version of this launcher [had a custom set of keys](https://github.com/SKCraft/SKMCLauncher/blob/83bb2deb1ae3350c700e40452570271fc4ea5e2f/src/main/java/com/sk89q/mclauncher/session/LegacySession.java#L78), but it completely replaced Java's and this became a problem whenever Mojang updated their certs, which broke login.

The previous launcher actually had full signing every step of the way but this way over everyone's head so I abandoned it.

**Comment by dscso** [comment]
Ok. This issue is null and void because Froge also downloads its dependencies without signing them.
