### ISSUE TITLE
[Question] Difference between single and multiple modpacks

### ISSUE THREAD

**Issue by utoc** [SKCraft/Launcher#162]
Hey guys

Quick question regarding the creator using a single/vs multiple modpacks.  When we're using a single modpack, each user is prompted every time to launch to select their optional client mods.  When we have a second pack, a beta version for testing for example, they're no longer prompted for optional mods unless an update is present.  I haven't found anything in the documentation that discusses this behavior or how to change it.  Can anyone shed some light on this?  I prefer the former behavior, for users to be prompted each time if that is possible.

Thanks

packages.json - http://pastebin.com/NK7m9CFx
pack 1 json - http://pastebin.com/5zkzm4zi
pack 2's json is nearly identical except its title and name fields and it contains a few extra mods.

**Comment by sk89q** [comment]
Users are prompted when the launcher updates the pack, which happens if the version the launcher has recorded for the pack differs from the version in packages.json. However when the launcher finishes updating, it will record the version from the pack.json and not from the packages.json file. 

If you are getting prompted every time, it means that the version in packages.json differs from the pack.json. If you want this behavior then make sure packages.json always has the wrong version, although checking for update every time can be annoying for users.

**Comment by utoc** [comment]
That makes sense because I don't update packages.json when we don't have the second beta pack.  Thanks sk89q.
