### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by StrayanDropbear** [SKCraft/Launcher#179]
Hello, everytime i start the modpack i'm getting this crash:
http://pastebin.com/qNjLPTkC

others can run it fine but for some reason I can't, It isn't my GPU considering other minecraft clients work perfectly fine. Also, everyone is getting this error:
**[06:12:03] [main/ERROR] [FML]: Unable to read the jar file jei_1.10.2-3.14.6.408.jar - ignoring
java.util.zip.ZipException: invalid END header (bad central directory offset)**

every mod is getting that error and not loading.

**Comment by sk89q** [comment]
Who do you mean by others?

**Comment by StrayanDropbear** [comment]
friends can launch it fine

**Comment by sk89q** [comment]
Through the launcher and not the modpack creator right?

**Comment by sk89q** [comment]
Through the launcher and not the modpack creator right?

On Feb 15, 2017 2:25 PM, "Michael" <notifications@github.com> wrote:

friends can launch it fine

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SKCraft/Launcher/issues/179#issuecomment-280160222>,
or mute
the thread

**Comment by StrayanDropbear** [comment]
launcher and through modpack creator doesn't work

**Comment by spannerman79** [comment]
This is **not** a launcher issue.
If you actually read your log file @StrayanDropbear you would have seen the following;

`org.lwjgl.LWJGLException: Pixel format not accelerated`
http://bfy.tw/A7Fg

**Comment by StrayanDropbear** [comment]
This only happens with SKCraft launcher and i did read my log file. also, this is a "Launcher" issue:
**[06:12:03] [main/ERROR] [FML]: Unable to read the jar file jei_1.10.2-3.14.6.408.jar - ignoring
java.util.zip.ZipException: invalid END header (bad central directory offset)**

**Comment by spannerman79** [comment]
All that states is that there is an issue with the actual mod itself.
Check its MD5 against https://minecraft.curseforge.com/projects/just-enough-items-jei/files/2380700

**Comment by sk89q** [comment]
When you said "everyone gets that error," did you mean every **mod** gets that error?

**Comment by StrayanDropbear** [comment]
everyone that tried installing the pack, it also happens to every mod.

**Comment by sk89q** [comment]
You say that your friends can run it fine but also that everyone can't run it. Can you clarify?

**Comment by StrayanDropbear** [comment]
I'm talking about the first issue "Pixel format not accelerated" i'm the only one having that issue.  Second issue affects everyone.

**Comment by sk89q** [comment]
Upgrade or downgrade your graphics drivers to fix the Pixel format issue. I haven't checked if you're using Nvidia but they released an update specifically to fix that issue and that has so far fixed it for everyone I've spoken to. 

The second issue is typically caused by uploading the modpack using FTP in auto or text mode instead of binary mode. You can find this setting in your FTP client.

**Comment by StrayanDropbear** [comment]
Yeah updating did fix that, just strange your launcher was only affected. going to try the second solution now.

**Comment by sk89q** [comment]
Did you get it fixed?

**Comment by StrayanDropbear** [comment]
Changing to binary mode didn't fix the issue, but reinstalling filezilla did. Have no idea how that fixed it. anyways, thanks for the help. :)
