### ISSUE TITLE
Cant change launcher name.

### ISSUE THREAD

**Issue by Eiple** [SKCraft/Launcher#192]
Hello, Im trying to change the launcher name but I dont know how.
this is my launcher.properties file : 
`version=0
agentName=Minecraft
offlinePlayerName=Player

versionManifestUrl=https://s3.amazonaws.com/Minecraft.Download/versions/%1$s/%1$s.json
librariesSource=https://libraries.minecraft.net/
jarUrl=https://s3.amazonaws.com/Minecraft.Download/versions/%1$s/%1$s.jar
assetsIndexUrl=https://s3.amazonaws.com/Minecraft.Download/indexes/%s.json
assetsSource=http://resources.download.minecraft.net/
yggdrasilAuthUrl=https://authserver.mojang.com/authenticate
resetPasswordUrl=https://minecraft.net/resetpassword

newsUrl=http://update.skcraft.com/template/news.html?version=%s
packageListUrl=http://update.skcraft.com/template/packages.json?key=%s
selfUpdateUrl=http://update.skcraft.com/template/launcher/latest.json
 
with that settings the tittle bar shows: SKCraft Launcher (v0), theres any way to add a custom name or just leave the SKCraft Launcher?
Also whats agent name for ? 
I dont know how to remove the version from the title bar. 
`

**Comment by sk89q** [comment]
It's in the language file which is a separate properties file.

As for the version, it may be that same file when you change the title.

On Jun 27, 2017 1:16 PM, "Eiple" <notifications@github.com> wrote:

Hello, Im trying to change the launcher name but I dont know how.
this is my launcher.properties file :
`version=0
agentName=Minecraft
offlinePlayerName=Player

versionManifestUrl=https://s3.amazonaws.com/Minecraft.
Download/versions/%1$s/%1$s.json
librariesSource=https://libraries.minecraft.net/
jarUrl=https://s3.amazonaws.com/Minecraft.Download/versions/%1$s/%1$s.jar
assetsIndexUrl=https://s3.amazonaws.com/Minecraft.Download/indexes/%s.json
assetsSource=http://resources.download.minecraft.net/
yggdrasilAuthUrl=https://authserver.mojang.com/authenticate
resetPasswordUrl=https://minecraft.net/resetpassword

newsUrl=http://update.skcraft.com/template/news.html?version=%s
packageListUrl=http://update.skcraft.com/template/packages.json?key=%s
selfUpdateUrl=http://update.skcraft.com/template/launcher/latest.json

with that settings the tittle bar shows: SKCraft Launcher (v0), theres any
way to add a custom name or just leave the SKCraft Launcher?
Also whats agent name for ?
I dont know how to remove the version from the title bar.
`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/SKCraft/Launcher/issues/192>, or mute the thread

**Comment by Eiple** [comment]
Thank you, working !
