### ISSUE TITLE
Minecraft not owned error

### ISSUE THREAD

**Issue by techmandan** [SKCraft/Launcher#255]
Hello.
I tried your launcher, but when I click Login, it says I don't own minecraft. But on that account, I own Java version, windows 10 edition and pocket edition. Why do I get these error, while official launcher and technic launcher works?

**Comment by techmandan** [comment]
Everything works normally, but I'm still geting that error... Why?

**Comment by Cyxo** [comment]
Up! I'm having the same error...

**Comment by AvnyrTokirawa** [comment]
Again with Java Edition and good ceditentials :/

**Comment by DarkScientist** [comment]
It's because you've changed the agent name.
If you want to modify it, you'll need to implement your own Yggdrasil auth system. 
Here are a few servers you'll have to install to get an yggdrasil server running :
1) https://github.com/Litarvan/OpenAuth-Server
2) MineWeb with Auth plugin
3) https://github.com/rutkai/Mjolnir-Authentication-Server for nodejs

**Comment by pigmen26gamesYT** [comment]
This Is not in english rip Open Auth

**Comment by DarkScientist** [comment]
So you've got the NODEJS auth server

**Comment by hedgehog1029** [comment]
Likely caused by changing the `agentName` property in launcher.properties - this should be left set to `Minecraft`.
