### ISSUE TITLE
Make a plugin / modules system

### ISSUE THREAD

**Issue by DarkScientist** [SKCraft/Launcher#297]
Hi,
I had an idea of making a plugin / module system. 
Does it exist or will it be added?

If I make it, how will I have to do?
 
I thought about plugins into the web server which are downloaded but I think most of them will need to be recompiled so, I'll have to put it as compiled with the launcher.

I thought about making an API and documentation to help you making a plugin. 

Are some people interested?
Let me know if you have any questions or suggestions.

**Comment by spannerman79** [comment]
> I had an idea of making a plugin / module system.
> Does it exist or will it be added?

Need to give an example of what and how it will function.
Its full purpose, etc.

In short - people that run servers, be it minecraft, httpd, etc have their own way of deplying "plugins" (jenkins, Travis, json feed from plugin devs that post over at SpigotMC etc).

Just stating "Who would be interested" is not enough.

**Comment by DarkScientist** [comment]
Hi,
I thought about making an API, a lib which allows you to do (for example) :
- HTTP requests with get / post with response analyzing
-Managing Mod packs with an easiest way than the creator tools (make paid
Mod packs, etc...)
-Adding buttons / windows or modifying the interface
-Making a money system
-Compatibility with a CMS which link the accounts through authentification
and which includes notifications / money / etc...
- And many more feature you can imagine...

**Comment by spannerman79** [comment]
> make paid Mod packs

Seriously? Your going to make money from other peoples hard work - including and not limited to the devs of https://github.com/MinecraftForge

You are a low life.

**Comment by DarkScientist** [comment]
I wasn't telling about real money but points you can give in game, and the mods should be from your development...

**Comment by DarkScientist** [comment]
And it's an idea by many others, I don't focus on this idea... Please read the entire post, it was only an example... I won't do it, but this is a thing you'll be able to do.

**Comment by spannerman79** [comment]
Ok then lets read over the "entire post" shall we

> HTTP requests with get / post with response analyzing

All you need to do is parse json - not exactly hard if you want to do that. And even if you don't know how you can easily get an add-on to whatever forum system is being used to parse json.

> Managing Mod packs with an easiest way than the creator tools (make paid Mod packs, etc...)

Seriously? My friends 9 year old daughter created a modpack with all the mods from curseforge herself using the creator tools with its GUI. If you want it "easier" then that then I question that persons intelligence.
I've already made my stance clear on the "paid modpacks" part.

> Adding buttons / windows or modifying the interface

So you want to make it more confusing for the "average" user.  No thanks, [KISS](https://www.interaction-design.org/literature/article/kiss-keep-it-simple-stupid-a-design-principle) should be used and kept.

> Making a money system

This screams Pay2Win, which is against Mojangs EULA. And any "money" system already in place that complies with Mojang's EULA doesn't need the inclusion into a launcher - that is just a gateway to abusing a loophole.

> Compatibility with a CMS which link the accounts through authentification and which includes notifications / money / etc...

The top cms/forums used for/with a minecraft community are (not in any particular order) Enjin, Invision, Xenforo & NamelessMC off the top of my head this very moment.  There are a couple others but those previously mentioned ones already have in place a way to sync forum users to MC account names - both paid and free solutions. If you run a grey/whitelist server those users would have already linked their MC name in order to gain access to even download the launcher to start with.

> And many more features you can imagine...

I'm not touching this one, this is a can of worms here...


So Yes I have already read through all of your post beforehand.

**Comment by DarkScientist** [comment]
I Will try to think about that.
