### ISSUE TITLE
[SUGGESTION] Get rid of releases

### ISSUE THREAD

**Issue by thisischrys** [SKCraft/Launcher#332]
I think a bunch of problems people are reporting (failing downloads) are because they are just using the releases instead of following the wiki.

I know the wiki has you build it yourself, maybe just remove the releases altogether if they're not being kept up to date.

**Comment by spannerman79** [comment]
Its more then just that.  Until @sk89q either accepts some of the PR's in place or make the changes himself just following the wiki isn't enough.

https://github.com/SKCraft/Launcher/issues/235 is the current issue that is affecting this launcher.  There are solutions in place that you need to either use yourself or to use those patch's against your own fork in order to make it function again.

**Comment by hedgehog1029** [comment]
:crab: the releases are gone :crab:
