### ISSUE TITLE
Fancy Launcher wont open

### ISSUE THREAD

**Issue by darealHeroBrine** [SKCraft/Launcher#382]
the title says it. it just wont open. and hadnt since i downloaded the source. it was fine up till now

**Comment by hedgehog1029** [comment]
if you can - open a command prompt/terminal in the folder next to the JAR and run `java -jar launcher-fancy-4.3-SNAPSHOT-all.jar` which should spit out some logs as to what went wrong.

an annoying part of Java is that if something goes wrong while loading the application it'll just fail silently. the new bootstrapper that I'm working on is aiming to fix that a little bit but obviously that's not helpful if you're not using a bootstrapper

**Comment by darealHeroBrine** [comment]
using the cmd promopt it opens but just double clicking it doesnt. does it need to be opned via bootstrap or cmd prompt? cuz i didnt see that in the wiki and i look every where in there

**Comment by hedgehog1029** [comment]
that's odd - it sounds like you might have different Java versions? if launching via command prompt works fine, then that java executable is a-ok - but double clicking will go via the shell (e.g. windows explorer) which might point to a different Java version?

the command line Java version is determined by the `PATH` environment variable, wheras double-click-to-launch is handled by Windows file associations. this is falling quickly into "too technical" territory, it'd be difficult to correct this manually... 

again, this is one of those annoying issues that comes with having a Java-based program - errors in the launch just get silently dropped, because user code has little to no control over the early environment. i'm hoping to fix these kinds of errors with [the new bootstrapper](https://github.com/SKCraft/rusty-bootstrapper) but it's not quite ready for prime time yet.

**Comment by darealHeroBrine** [comment]
thank you for the help and info tho. :) i say this has been resolved dont you?
