### ISSUE TITLE
Skinprovider https://visage.surgeplay.com/ seems to be unreliable

### ISSUE THREAD

**Issue by johnfriedrich** [SKCraft/Launcher#400]
Hi,
Skinprovider https://visage.surgeplay.com/ seems to be unreliable. I suggest adding another one as fallback, for example https://minotar.net/ which was reliable in the past or use the default steve head when the request should fail

**Comment by hedgehog1029** [comment]
I just tested minotar and it appears to just return the Steve face every time, which is, uh, one way of doing it.

I will make sure to catch the error though, so it can fall back gracefully. Ideally I'd like to just use the Mojang/Microsoft APIs to extract the skin directly, since we're already calling into those APIs... but then I have to run em through processing which might be difficult to implement.

**Comment by johnfriedrich** [comment]
Weird, works for me
`String skinUrl = String.format("https://minotar.net/avatar/%s/32.png", uuid);`
Anyway, thanks for looking into it

**Comment by hedgehog1029** [comment]
OK I looked into it and processing the full skin isn't that difficult. So I've implemented that in 5d5a462387c6550f2c9ecda6711efbf707e927ba, which should resolve this issue.

**Comment by johnfriedrich** [comment]
Awesome thanks! Thanks very much for putting so much effort into this project lately. Really appreciate that!
