### ISSUE TITLE
Removal of Pack200 Support Breaks Backward Compatibility

### ISSUE THREAD

**Issue by MadMartian** [SKCraft/Launcher#404]
The bootstrap launcher tries to download and execute a pack200 file as a Java JAR and (logically) fails.  This is because pack200 support was removed from the bootstrap launcher without any backward compatibility handling for old bootstrap launchers that require a pack200 launcher binary.

As a work around a user can download a new bootstrap launcher that should point to a different meta-update URL than legacy bootstrap launchers (to mitigate mutual incompatibilities).  The developer must then maintain two separate copies of the latest launcher, one that is pack200 for the legacy bootstrap launcher and one that is a plain JAR for the new bootstrap launchers.

**Comment by MadMartian** [comment]
Nope, doesn't work.  The new bootstrap launcher ignores the bundled meta update URL and chooses the one in an old launcher JAR.

**Comment by hedgehog1029** [comment]
The situation around pack200 is a bit of an unavoidable mess - the problem lies in the fact that pack200 was completely removed from the JRE in Java 14. So old bootstrappers are just gonna stop working eventually anyway because they assume that pack200 will always be available. And since the bootstrapper doesn't self-update there is no easy way to fix this.

However, there is a common misunderstanding at play here. The bootstrapper is only responsible for downloading the launcher *initially*, after which it will **never** download another file, *unless it cannot find a working launcher jar*. As long as there is a working launcher JAR, it will simply launch that without checking for an update. The launcher is responsible for updating itself, NOT the bootstrapper. Therefore, for non-packed updates to work, you need to push a launcher update.

Maintaining two seperate latest.json files is the recommended migration path - though I would recommend basically upgrading the old file to the latest (packed) version once and then leaving it alone, and just start maintaining a different file. This way, old launcher installations can upgrade to a launcher version with the new latest.json URL configured, and then update further from there correctly without bothering with the whole pack200 nonsense.

(Basically the idea is that *only* old bootstrappers should point at the old `latest.json` - everything else, including the packed launcher downloaded by old bootstrappers, should point to the new `latest.json`. You will also have legacy launcher installations in the wild pointing at the old`latest.json`, but they will read that file and discover there is an update available and will thusly update themselves to a working launcher version)

Also, since the launcher self-updater doesn't save a `.jar.pack` file, simply a `.jar`, old bootstrappers will continue to work fine with new launchers (though obviously it will only redownload the packed version in the case of corruption). All the new bootstrapper does compared to the old one is refuse to operate on a `.jar.pack` file, and also save the file as a `.jar` correctly.

**Comment by MadMartian** [comment]
Ok it sounds like we're on the same page, I think the reason I couldn't get it to work is because I added the field `packed` to the oldest `latest.json` and that broke JSON parsing, but it looks like it's required in the latest version.  So now my concern is if an updated launcher decides to pull from the oldest `latest.json` (instead of the newest `latest.json`) and JSON parsing breaks _that_ way because it _expects_ a `packed` field, but would an updated launcher do that if I changed the self-update URL configured in its proprerties to point to the newest `latest.json` prior to publishing it?

Taking a step back, removal of Pack200 makes sense to me because JAR files are Zip compressed already anyway.  Maybe there was another motivation, firewalls have been known to quarantine JAR files, but I digress.

**Comment by hedgehog1029** [comment]
I removed the `packed` field completely when I ganked out pack200, and tbh I shouldn't have added it in the first place. If you're up-to-date with the master branch you shouldn't need it. Is that still in the wiki somewhere? I thought I removed references to it.

I just had a look at the code and it looks like there was a missing "ignore unknown properties" annotation, but that doesn't explain why it would expect a `packed` field, it just means that any other unknown fields being present would throw an error. The bootstrapper also doesn't expect any fields except `url` (even when `packed` existed I made sure not to rely on it existing, because old `latest.json`s wouldn't have that key). So I'm not sure what you're encountering.

>  So now my concern is if an updated launcher decides to pull from the oldest latest.json (instead of the newest latest.json)

Why would an *updated* launcher pull from the old `latest.json`? I assume you recognize that the new one should be at a new URL, e.g. `http://example.com/launcher/latest-v2.json`. If you've set the selfUpdateUrl in the updated launcher it will only pull from that URL.

**Comment by hedgehog1029** [comment]
> I added the field `packed` to the oldest `latest.json` and that broke JSON parsing

Oh, actually because of the missing "ignore unknown properties" that would throw an error on very old launcher versions (but not in the bootstrapper, notably).
But as I said above `packed` isn't needed anywhere so just get rid of it.

**Comment by MadMartian** [comment]
> If you've set the selfUpdateUrl in the updated launcher it will only pull from that URL.

Ok cool, just wanted to get clarification on that.

> I removed the `packed` field completely when I ganked out pack200, and tbh I shouldn't have added it in the first place. If you're up-to-date with the master branch you shouldn't need it. Is that still in the wiki somewhere? I thought I removed references to it.

Still present in [LatestVersionInfo](https://github.com/SKCraft/Launcher/blob/master/launcher/src/main/java/com/skcraft/launcher/selfupdate/LatestVersionInfo.java)

**Comment by hedgehog1029** [comment]
It's present but it's ignored - the launcher doesn't read it. Now that I've added the annotation to that data class I could remove it, actually. But it shouldn't affect anything as-is.

**Comment by MadMartian** [comment]
Ok I think we can close this ticket, thanks for the explanation.
