### ISSUE TITLE
Large files aren't downloading completely.

### ISSUE THREAD

**Issue by crdnl** [SKCraft/Launcher#407]
**Short Description:** Started working on a ModPack for some friend and myself and some of us are having a weird problem, some JAR files aren't downloaded properly.

**Long Description:** I created and uploaded a modpack to my webserver, `minecraft.sso.gg`, and although two users can download it properly, 4 others have had to get a copy of the larger of the files, notably Astral Sorcery (28.6 MB) and MineColonies (36.2 MB) as they seem to receive only partial downloads of the files.

**Replication:**
1. Find some way to limit Java to 1MB/s. I used TMeter, you could theorhetically use a SOCKS proxy to accomplish the same.
2. Download and launch https://minecraft.sso.gg/FractalSMP.jar
3. Attempt to download the `FractalSMP` Modpack
4. When launched, Forge should throw " `x`is not a jar file"

**Environment:**
* JDK: OpenJDK jdk-8.0.272.10-hotspot (Used for Building and running the launcher)
* OS: Windows 10 (20H2)
* Webserver: halverneus/static-file-server (Reverse Proxied by Pomerium)

**Notes:**
* I wanted to rule out the server, so I did a `curl` to the server, with `curl https://minecraft.sso.gg/objects/62/64/6264f6ff1d1e546a22afa51019c5ebbcf7452bc3 --limit-rate 300k --output tmp.jar`. This is Astral Sorcery's jar file. The download was fine, and worked successfully, even down to 300kbps.
* Feel free to hit the server with testing, or if you need additional information let me know.
* The modpack was build using the graphical `creator-tools` package, and uploaded to the server using FileZilla.

**Comment by hedgehog1029** [comment]
If you've been able to replicate the issue, could you post the corrupted file somewhere? It would be interesting to see what it looks like.

**Comment by crdnl** [comment]
Uploaded to https://minecraft.sso.gg/broken/astralsorcery-1.16.4-1.13.9.jar-dead:

Notably opening then up with a HEX editor, the broken version cuts off at `71fff0`, while the working file continues past, ending at `01caaf10`. The actual content of the files is an exact match up until `71fff0`.

It looks like `com.skcraft.launcher.util.HttpRequest` is hitting some time limit (30s?) then killing the connection before the file finishes downloading. It looks like the files aren't getting validated when they're finished. Looking at the source, the read timeout is set to 60s though.

**Comment by hedgehog1029** [comment]
If it was the read timeout I'd expect it to throw a `SocketTimeoutException` and report the failed download (download i/o errors are caught and reported).

Files are not validated after downloading, correct - partly since TCP and HTTP are assumed to be reliable, and partly because the hash is mostly used for update checking.

There are a couple of details here that lead me to suspect a similar situation to #385...

1. File downloads are saved with a `.tmp` extension initially, before being renamed to the original filename. However, if an exception is raised, this rename won't happen. So the fact the files are named correctly implies that Java detected absolutely nothing wrong with the download.
2. Also, that's all in a temporary install directory, so the entire download step also has to finish before files are moved over.
3.
```
 57 28.6M   57 16.4M    0     0   301k      0  0:01:37  0:00:55  0:00:42  299k
* transfer closed with 11906847 bytes remaining to read
* stopped the pause stream!
* Connection #0 to host minecraft.sso.gg left intact
curl: (18) transfer closed with 11906847 bytes remaining to read
```

I think your static file server (or proxy) might be closing transfers early?

Whether this is valid behaviour is probably up for debate (though curl certainly just exited rather than retrying). The server is specifying `accept-ranges: bytes` which means it probably intends for clients to detect an early close and make a new request specifying a byte range. The launcher doesn't support that - and usually that feature is reserved for serving video, since it allows clients to seek around quickly.

I *am* surprised that the launcher doesn't detect this. But then again, curl seemed kinda surprised? I haven't figured out exactly what is happening on the wire when curl reports this - I think the TCP connection was fine (judging by the `left intact` line), but I guess it somehow detected that the server didn't want to send any more bytes?

If it is just stopping the transfer silently, which it clearly knows somehow, I can at least detect (like curl) that the received byte count is not equal to the `Content-Length` specified in the response, and throw an error.

**Comment by crdnl** [comment]
Did some more digging on my side. Looking through the Pomerium config, I noticed that I had set the _global_ read timeout to 60m, but there is a _per route_ timeout that defaults to 30s. A config change and it doesn't seem to be reproducible.

So, I guess the bug is that it doesn't detect the wrong file size, even if the server cleanly cuts the connection.

**Comment by hedgehog1029** [comment]
Should be fixed in master.
