### ISSUE TITLE
windows forge 1.12 error download

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [SKCraft/Launcher#419]
I don't quite understand why the client doesn't download on windows forge 1.12. this works on ubuntu and the 1.16 client works on windows, but for some reason in this situation it is looking for a file that it has not downloaded yet.
`To report this error, please provide:
java.io.FileNotFoundException: C:\Users\\Desktop\instances\mod\manifest.json (The filename, directory name, or volume label syntax is incorrect)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at java.io.FileOutputStream.<init>(Unknown Source)
	at com.skcraft.launcher.util.HttpRequest$BufferedResponse.saveContent(HttpRequest.java:597)
	at com.skcraft.launcher.update.BaseUpdater.installPackage(BaseUpdater.java:91)
	at com.skcraft.launcher.update.Updater.update(Updater.java:165)
	at com.skcraft.launcher.update.Updater.call(Updater.java:97)
	at com.skcraft.launcher.update.Updater.call(Updater.java:40)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

**Comment by hedgehog1029** [comment]
`C:\Users\\Desktop\instances\mod\manifest.json (The filename, directory name, or volume label syntax is incorrect)`

Looks like you've somehow ended up with a broken path; I'd expect that path to have a username in it (like `C:\Users\Name\Desktop`).  
Also it's shoving stuff onto the desktop because it hasn't been bootstrapped - might be worth putting it in another folder to keep the extra files & folders from polluting your desktop.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> `C:\Users\\Desktop\instances\mod\manifest.json (The filename, directory name, or volume label syntax is incorrect)`
> 
> Looks like you've somehow ended up with a broken path; I'd expect that path to have a username in it (like `C:\Users\Name\Desktop`).
> Also it's shoving stuff onto the desktop because it hasn't been bootstrapped - might be worth putting it in another folder to keep the extra files & folders from polluting your desktop.

I cut out confidential information. in any case, this does not work on windows in any way, and only this version

**Comment by hedgehog1029** [comment]
Ah, OK. That makes this slightly less confusing, at least.

Did you also redact the folder name there (`mod`)? Because a good thing to check would be whether that folder name is valid - does it exist on the filesystem?
The launcher appears to be failing to write the manifest file during the initial package update step.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> Ah, OK. That makes this slightly less confusing, at least.
> 
> Did you also redact the folder name there (`mod`)? Because a good thing to check would be whether that folder name is valid - does it exist on the filesystem?
> The launcher appears to be failing to write the manifest file during the initial package update step.

the client folder does not exist in principle, logically, because the launcher does not download it. from the point of view of the download server, all other clients work, so everything is fine on ubuntu

**Comment by hedgehog1029** [comment]
the launcher doesn't "download" folders, that doesn't make any sense. it makes the folders and downloads the files that need to go in those folders.

I can see from the stack trace that it's failing to **create** the manifest file, which is the first step of the pack installation. This could be for multiple reasons:

1) The parent folder structure doesn't exist. (e.g. the `mod` folder is missing) - the launcher tries to create this folder but I believe it's silent on failure, since the error is also thrown if the folder already exists. This one sounds the most likely from what you've said so far.
2) The launcher process doesn't have the permission to create the manifest file. Unlikely if the folder was successfully created.
3) Some other I/O problem occurred while creating the folder or file.

**Comment by Envel-Nikita-Gutsenkov** [comment]
> 
> 
> the launcher doesn't "download" folders, that doesn't make any sense. it makes the folders and downloads the files that need to go in those folders.
> 
> I can see from the stack trace that it's failing to **create** the manifest file, which is the first step of the pack installation. This could be for multiple reasons:
> 
>     1. The parent folder structure doesn't exist. (e.g. the `mod` folder is missing) - the launcher tries to create this folder but I believe it's silent on failure, since the error is also thrown if the folder already exists. This one sounds the most likely from what you've said so far.
> 
>     2. The launcher process doesn't have the permission to create the manifest file. Unlikely if the folder was successfully created.
> 
>     3. Some other I/O problem occurred while creating the folder or file.

the interesting thing is that everything works on ubuntu, just as other clients work on windows, but this particular one does not. I tried doing a full folder reset but it didn't help.

that is 1.16 I have started and everything is ok
1.12 - no
