### ISSUE TITLE
Option to specify different Java version for a pack

### ISSUE THREAD

**Issue by Kore-Development** [SKCraft/Launcher#421]
I use Java 11, but I have a pack that needs Java 8 and crashes on Java 11. Could an option be added where for example the global Java version is Java 11, but this specific pack could use Java 8?

**Comment by hedgehog1029** [comment]
Right now you should probably just set the java version in the launcher settings to Java 8. I appreciate that you might want the new GC though.

However, I think something like this will only become more important as 1.17 releases with a reliance on Java 16; since old modded versions are unlikely to run under Java 9+, we'll need a better way to specify Java version restrictions.

Along with this I want to look into using the vanilla Minecraft launcher's bundled java to avoid users having to install another copy system-wide.

**Comment by Kore-Development** [comment]
For me, these are the Java versions I usually need for each version.
1.12 and before: Java 8
1.13-1.16: Java 11 (Java 8 compatible but you may need LetsEncryptCraft for some things)
1.17+: Java 16

**Comment by hedgehog1029** [comment]
With the closing of #443 this should also be resolved.
