### ISSUE TITLE
Incorrect SHA for almost all libraries

### ISSUE THREAD

**Issue by HarrisFauntleroy** [SKCraft/Launcher#430]
I have everything set up, and 99% of stuff works. 
And this may well be a fedora linux issue...

But when I click download pack from the launcher it gets most of the way through and always fails on the hash comparison of all the ASM libraries.
Correction not just ASM, now moddownloader package too.

Ill try deleting all the libraries and regenerating and report back.

I tried just not providing the asm libraries but they populate when the pack builds

any thoughts?

**Comment by hedgehog1029** [comment]
Last time this happened it was because the web server was doing some "smart correction" - basically redirecting URLs that should 404 to other files with similar paths.

When downloading libraries, the launcher looks in two places: your webserver, and `libraries.minecraft.net`. It checks your webserver first and expects it to return a 404 if there's no file there; but if your webserver returns a different file it will just use that because, well, your webserver says it's the right file. If you tell me the hashes I might be able to identify if it's doing that.

**Comment by HarrisFauntleroy** [comment]
Once again, user error on my part.
Using ?raw=true is not the same as using a raw.github link when using github pages. Not sure why but the former only half works and the latter fully works. All running without issues now.
